import { Playlist } from '../Models/Playlist';
import { Track } from '../Models/Track';
import { User } from '../Models/User';

var playlist = new Playlist(
    'Playlist name',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    'https://muzikercdn.com/uploads/products/3730/373019/c118cded.jpg',
    '01 - 10 - 1982',
    21,
    new User(
        'Username',
        'https://t3.ftcdn.net/jpg/01/41/81/30/360_F_141813016_vrZ4TFKphl7vLBty0kfQmIAEjFgtkJzW.jpg'
    )
)

var track = new Track(
    {
        thumbnail: 'https://muzikercdn.com/uploads/products/3730/373019/c118cded.jpg',
        title: 'Dirty Pool',
        uploader: 'Stevie Ray Vaughan & Double Trouble',
        duration: 301,
        viewCount: 393457,
        likes: 7600,
        dislikes: 630,
        description: 'Provided to YouTube by Sony Music Entertainment\nDirty Pool · Stevie Ray Vaughan & Double Trouble\nTexas Flood (Legacy Edition)\n℗ 1983 Epic Records, a division of Sony Music Entertainment\nReleased on: 2013-01-25\nGuitar, Vocal, Composer, Lyricist, Producer: Stevie Ray Vaughan\nDrums: Chris "Whipper" Layton\nComposer, Lyricist: Doyle Bramhall\nAssociated  Performer, Producer: Double Trouble\nBass: Tommy Shannon\nProducer, Recording  Engineer: Richard Mullen\nExecutive  Producer: John Hammond\nAssistant  Producer: Mikie Harris\nAssistant  Engineer: Don Wershba\nAssistant  Engineer: Harry Spiridakis\nMixing  Engineer: Lincoln Clapp\nAuto-generated by YouTube.',
        dateUploaded: '26 jan. 2017',
    }
)

var playlistSelected = new Playlist(
    'Playlist name',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    'https://muzikercdn.com/uploads/products/3730/373019/c118cded.jpg',
    '01 - 10 - 1982',
    21,
    new User(
        'Username',
        'https://t3.ftcdn.net/jpg/01/41/81/30/360_F_141813016_vrZ4TFKphl7vLBty0kfQmIAEjFgtkJzW.jpg'
    ),
)

playlistSelected.tracks = [
    track,
    track,
    track,
    track,
    track,
    track,
    track,
    track,
    track,
    track,
    track,
    track,
    track,
    track,
    track,
    track,
    track,
    track,
]

playlistSelected.selected = true;

const initialStatePlaylist = {
    loading: false,
    playlists: [
        playlistSelected,
        playlist,
        playlist,
        playlist,
        playlist,
        playlist,
        playlist,
        playlist,
        playlist,
        playlist,
        playlist,
        playlist,
        playlist,
        playlist,
    ]
}

const playlistActions = {
    LOADED_PLAYLISTS: 'LOADED_PLAYLISTS'
}

const PlaylistReducer = (state = initialStatePlaylist, action) => {
    switch (action.type) {
        case playlistActions.LOADED_PLAYLISTS:
            return { ...state, playlists: action.playlists };
        default:
            return state;
    }
}

export default PlaylistReducer;